// <auto-generated>
//   此文件由 T4 模板 AtomicValueType.tt 自动生成，请勿手动修改。
//   重新生成：在 Visual Studio 中右键 .tt 文件 → "运行自定义工具"，
//             或使用命令行：dotnet-t4 AtomicValueType.tt
// </auto-generated>

// ***********************************************************************
// 文件名：         AtomicValueType.cs
// 创建日期：       2026/04/05
// 作者：           nekopunch  [T4 自动生成]
// ***********************************************************************

using System;
using System.Runtime.CompilerServices;
using System.Threading;

namespace WaveKits
{
    /// <summary>
    /// 线程安全的 <see cref="int"/> 原子容器。
    /// <para>
    /// 所有操作通过 <see cref="Interlocked"/> 或 <see cref="Volatile"/> 保证原子性与线程间可见性。
    /// </para>
    /// </summary>
    public sealed class AtomicInt
    {
        private int _value;

        public AtomicInt(int value = 0) => _value = value;

        // ── Load / Store ──────────────────────────────────────────────────

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public int Load() => Volatile.Read(ref _value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Store(int newValue) => Volatile.Write(ref _value, newValue);

        // ── Increment / Decrement / Add ───────────────────────────────────

        /// <summary>原子自增 1，返回自增后的值。</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public int Increment() => Interlocked.Increment(ref _value);

        /// <summary>原子自减 1，返回自减后的值。</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public int Decrement() => Interlocked.Decrement(ref _value);

        /// <summary>原子加法，返回加法后的值。</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public int Add(int delta) => Interlocked.Add(ref _value, delta);

        public int Value
        {
            get => Load();
            set => Store(value);
        }

        // ── Exchange ──────────────────────────────────────────────────────

        /// <summary>原子 Exchange，返回旧值。</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public int Exchange(int newValue) => Interlocked.Exchange(ref _value, newValue);

        // ── CompareAndSet / CompareExchange ───────────────────────────────

        /// <summary>原子 CAS，返回是否成功。</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool CompareAndSet(int expected, int newValue) => Interlocked.CompareExchange(ref _value, newValue, expected) == expected;

        /// <summary>原子 CAS，返回替换前旧值。</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public int CompareExchange(int expected, int newValue) => Interlocked.CompareExchange(ref _value, newValue, expected);

        // ── Update（CAS 自旋）────────────────────────────────────────────

        /// <summary>CAS 自旋更新，返回新值。</summary>
        public int Update(Func<int, int> updateFunc)
        {
            int current, next;
            do
            {
                current = Load();
                next    = updateFunc(current);
            } while (!CompareAndSet(current, next));

            return next;
        }

        /// <summary>CAS 自旋更新，返回更新前的旧值。</summary>
        public int GetAndUpdate(Func<int, int> updateFunc)
        {
            int current, next;
            do
            {
                current = Load();
                next    = updateFunc(current);
            } while (!CompareAndSet(current, next));

            return current;
        }

        // ── 隐式转换 ──────────────────────────────────────────────────────

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator int(AtomicInt a) => a.Load();

        public override string ToString() => Load().ToString();
    }
    /// <summary>
    /// 线程安全的 <see cref="long"/> 原子容器。
    /// <para>
    /// 所有操作通过 <see cref="Interlocked"/> 或 <see cref="Volatile"/> 保证原子性与线程间可见性。
    /// </para>
    /// </summary>
    public sealed class AtomicLong
    {
        private long _value;

        public AtomicLong(long value = 0L) => _value = value;

        // ── Load / Store ──────────────────────────────────────────────────

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public long Load() => Interlocked.Read(ref _value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Store(long newValue) => Interlocked.Exchange(ref _value, newValue);

        // ── Increment / Decrement / Add ───────────────────────────────────

        /// <summary>原子自增 1，返回自增后的值。</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public long Increment() => Interlocked.Increment(ref _value);

        /// <summary>原子自减 1，返回自减后的值。</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public long Decrement() => Interlocked.Decrement(ref _value);

        /// <summary>原子加法，返回加法后的值。</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public long Add(long delta) => Interlocked.Add(ref _value, delta);

        public long Value
        {
            get => Load();
            set => Store(value);
        }

        // ── Exchange ──────────────────────────────────────────────────────

        /// <summary>原子 Exchange，返回旧值。</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public long Exchange(long newValue) => Interlocked.Exchange(ref _value, newValue);

        // ── CompareAndSet / CompareExchange ───────────────────────────────

        /// <summary>原子 CAS，返回是否成功。</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool CompareAndSet(long expected, long newValue) => Interlocked.CompareExchange(ref _value, newValue, expected) == expected;

        /// <summary>原子 CAS，返回替换前旧值。</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public long CompareExchange(long expected, long newValue) => Interlocked.CompareExchange(ref _value, newValue, expected);

        // ── Update（CAS 自旋）────────────────────────────────────────────

        /// <summary>CAS 自旋更新，返回新值。</summary>
        public long Update(Func<long, long> updateFunc)
        {
            long current, next;
            do
            {
                current = Load();
                next    = updateFunc(current);
            } while (!CompareAndSet(current, next));

            return next;
        }

        /// <summary>CAS 自旋更新，返回更新前的旧值。</summary>
        public long GetAndUpdate(Func<long, long> updateFunc)
        {
            long current, next;
            do
            {
                current = Load();
                next    = updateFunc(current);
            } while (!CompareAndSet(current, next));

            return current;
        }

        // ── 隐式转换 ──────────────────────────────────────────────────────

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator long(AtomicLong a) => a.Load();

        public override string ToString() => Load().ToString();
    }
    /// <summary>
    /// 线程安全的 <see cref="float"/> 原子容器。
    /// <para>
    /// 所有操作通过 <see cref="Interlocked"/> 或 <see cref="Volatile"/> 保证原子性与线程间可见性。
    /// </para>
    /// </summary>
    public sealed class AtomicFloat
    {
        private float _value;

        public AtomicFloat(float value = 0f) => _value = value;

        // ── Load / Store ──────────────────────────────────────────────────

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public float Load() => Volatile.Read(ref _value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Store(float newValue) => Volatile.Write(ref _value, newValue);

        public float Value
        {
            get => Load();
            set => Store(value);
        }

        // ── Exchange ──────────────────────────────────────────────────────

        /// <summary>原子 Exchange，返回旧值。</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public float Exchange(float newValue) => Interlocked.Exchange(ref _value, newValue);

        // ── CompareAndSet / CompareExchange ───────────────────────────────

        /// <summary>原子 CAS，返回是否成功。</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool CompareAndSet(float expected, float newValue) => Interlocked.CompareExchange(ref _value, newValue, expected) == expected;

        /// <summary>原子 CAS，返回替换前旧值。</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public float CompareExchange(float expected, float newValue) => Interlocked.CompareExchange(ref _value, newValue, expected);

        // ── Update（CAS 自旋）────────────────────────────────────────────

        /// <summary>CAS 自旋更新，返回新值。</summary>
        public float Update(Func<float, float> updateFunc)
        {
            float current, next;
            do
            {
                current = Load();
                next    = updateFunc(current);
            } while (!CompareAndSet(current, next));

            return next;
        }

        /// <summary>CAS 自旋更新，返回更新前的旧值。</summary>
        public float GetAndUpdate(Func<float, float> updateFunc)
        {
            float current, next;
            do
            {
                current = Load();
                next    = updateFunc(current);
            } while (!CompareAndSet(current, next));

            return current;
        }

        // ── 隐式转换 ──────────────────────────────────────────────────────

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator float(AtomicFloat a) => a.Load();

        public override string ToString() => Load().ToString();
    }
    /// <summary>
    /// 线程安全的 <see cref="double"/> 原子容器。
    /// <para>
    /// 所有操作通过 <see cref="Interlocked"/> 或 <see cref="Volatile"/> 保证原子性与线程间可见性。
    /// </para>
    /// </summary>
    public sealed class AtomicDouble
    {
        private long _value;

        public AtomicDouble(double value = 0.0) => _value = BitConverter.DoubleToInt64Bits(value);

        // ── Load / Store ──────────────────────────────────────────────────

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public double Load() => BitConverter.Int64BitsToDouble(Interlocked.Read(ref _value));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Store(double newValue) => Interlocked.Exchange(ref _value, BitConverter.DoubleToInt64Bits(newValue));

        public double Value
        {
            get => Load();
            set => Store(value);
        }

        // ── Exchange ──────────────────────────────────────────────────────

        /// <summary>原子 Exchange，返回旧值。</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public double Exchange(double newValue) => BitConverter.Int64BitsToDouble(Interlocked.Exchange(ref _value, BitConverter.DoubleToInt64Bits(newValue)));

        // ── CompareAndSet / CompareExchange ───────────────────────────────

        /// <summary>原子 CAS，返回是否成功。</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool CompareAndSet(double expected, double newValue) => Interlocked.CompareExchange(ref _value, BitConverter.DoubleToInt64Bits(newValue), BitConverter.DoubleToInt64Bits(expected)) == BitConverter.DoubleToInt64Bits(expected);

        /// <summary>原子 CAS，返回替换前旧值。</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public double CompareExchange(double expected, double newValue) => BitConverter.Int64BitsToDouble(Interlocked.CompareExchange(ref _value, BitConverter.DoubleToInt64Bits(newValue), BitConverter.DoubleToInt64Bits(expected)));

        // ── Update（CAS 自旋）────────────────────────────────────────────

        /// <summary>CAS 自旋更新，返回新值。</summary>
        public double Update(Func<double, double> updateFunc)
        {
            double current, next;
            do
            {
                current = Load();
                next    = updateFunc(current);
            } while (!CompareAndSet(current, next));

            return next;
        }

        /// <summary>CAS 自旋更新，返回更新前的旧值。</summary>
        public double GetAndUpdate(Func<double, double> updateFunc)
        {
            double current, next;
            do
            {
                current = Load();
                next    = updateFunc(current);
            } while (!CompareAndSet(current, next));

            return current;
        }

        // ── 隐式转换 ──────────────────────────────────────────────────────

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator double(AtomicDouble a) => a.Load();

        public override string ToString() => Load().ToString();
    }
    /// <summary>
    /// 线程安全的 <see cref="bool"/> 原子容器。
    /// <para>
    /// 所有操作通过 <see cref="Interlocked"/> 或 <see cref="Volatile"/> 保证原子性与线程间可见性。
    /// </para>
    /// </summary>
    public sealed class AtomicBool
    {
        private int _value;

        public AtomicBool(bool value = false) => _value = (value ? 1 : 0);

        // ── Load / Store ──────────────────────────────────────────────────

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool Load() => (Volatile.Read(ref _value) == 1);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Store(bool newValue) => Volatile.Write(ref _value, (newValue ? 1 : 0));

        public bool Value
        {
            get => Load();
            set => Store(value);
        }

        // ── Exchange ──────────────────────────────────────────────────────

        /// <summary>原子 Exchange，返回旧值。</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool Exchange(bool newValue) => (Interlocked.Exchange(ref _value, (newValue ? 1 : 0)) == 1);

        // ── CompareAndSet / CompareExchange ───────────────────────────────

        /// <summary>原子 CAS，返回是否成功。</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool CompareAndSet(bool expected, bool newValue) => Interlocked.CompareExchange(ref _value, (newValue ? 1 : 0), (expected ? 1 : 0)) == (expected ? 1 : 0);

        /// <summary>原子 CAS，返回替换前旧值。</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool CompareExchange(bool expected, bool newValue) => (Interlocked.CompareExchange(ref _value, (newValue ? 1 : 0), (expected ? 1 : 0)) == 1);

        // ── Update（CAS 自旋）────────────────────────────────────────────

        /// <summary>CAS 自旋更新，返回新值。</summary>
        public bool Update(Func<bool, bool> updateFunc)
        {
            bool current, next;
            do
            {
                current = Load();
                next    = updateFunc(current);
            } while (!CompareAndSet(current, next));

            return next;
        }

        /// <summary>CAS 自旋更新，返回更新前的旧值。</summary>
        public bool GetAndUpdate(Func<bool, bool> updateFunc)
        {
            bool current, next;
            do
            {
                current = Load();
                next    = updateFunc(current);
            } while (!CompareAndSet(current, next));

            return current;
        }

        // ── 隐式转换 ──────────────────────────────────────────────────────

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator bool(AtomicBool a) => a.Load();

        public override string ToString() => Load().ToString();
    }
}
